services:
  mediamtx:
    image: bluenviron/mediamtx:1
    container_name: aqara-mediamtx
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - ./recordings:/recordings
